apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpa-concepts-deployment
  labels:
    app: jpa-concepts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jpa-concepts
  template:
    metadata:
      labels:
        app: jpa-concepts
    spec:
      containers:
      - name: jpa-concepts
        image: ajay0079/my-docker-hub:latest-1.2
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
      imagePullSecrets:
      - name: dockerhub-secret