apiVersion: v1
kind: Service
metadata:
  name: jpa-concepts-service
spec:
  selector:
    app: jpa-concepts
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30941